### ISSUE TITLE
Tu é autista mano?

### ISSUE THREAD

**Issue by dokyo-ch** [stfxz/typescript-bot#2]
https://github.com/stfxz/typescript-bot/blob/afcfdd64a1ae762ddbeed4bb4710e24de615c778/src/client/DiscordClient.ts#L28

**Comment by stfxz** [comment]
o que mano quem e vc e qual o problema disso

**Comment by dokyo-ch** [comment]
tu tá setando aliases numa coleção mano

**Comment by stfxz** [comment]
eh, costume, isso ai ñ vai matar ninguem nao
